# Generated by Django 2.2 on 2019-05-16 16:23

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=2, validators=[sales.models.gender_validation]),
        ),
    ]
